version: '3.3'

services:
  mongo:
    image: mongo:4.4.9
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"

  rabbitmq2:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"

  api2:
    build: ./api
    image: api4
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBIT_HOST=rabbitmq2
      - RABBIT_PORT=5672
      - RABBIT_QUEUE_NAME=q
      - CONNECTION_STRING=mongodb://root:root@mongo:27017
      - DATABASE_NAME=172172_DB
    ports:
      - "2172:80"
    restart: on-failure
    depends_on:
      - rabbitmq2
  
  front2:
    build: ./dotnet-front
    image: front2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BASE_URL=http://api2:80
    ports:
      - "8091:80"
    restart: on-failure
    depends_on:
      - api2
