version: '3.3'

services:
    
  rabbitmq2:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"

  api2:
    image: grzegorzrychlicki/si_api:3.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBIT_HOST=rabbitmq2
      - RABBIT_PORT=5672
      - RABBIT_QUEUE_NAME=q
      - CONNECTION_STRING=mongodb://root:student@actina15.maas:27017
      - DATABASE_NAME=172172_DB
    ports:
      - "2172:80"
    restart: on-failure
    depends_on:
      - rabbitmq2
  
  front2:
    image: grzegorzrychlicki/si_front:1.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BASE_URL=http://api2:80
    ports:
      - "8091:80"
    depends_on:
      - api2
    
